### ISSUE TITLE
Grommet-cli and Yarn run script issue

### ISSUE THREAD

**Issue by arjunbm468** [grommet/grommet-cli#24] opened 2017-03-20 12:03 UTC
I have created the sample application using the NPM instructions as per https://grommet.github.io/docs/get-started

I found an strange issue, not sure whether that grommet-cli issue or yarn issue.
The **npm test**  command works fine but **yarn test** does not work.

**yarn test** just waits for some input from the keyboard like enter key then it starts executing.

I have used GIT BASH and Cygwin for reproducing the issue.
But there are no issues in Windows command prompt though.

Could you please help me on this topic.

Screen shot:
![capture](https://cloud.githubusercontent.com/assets/18460656/24098942/f470e446-0d92-11e7-938b-eebe206dcf8d.PNG)

**Comment by arjunbm468** [comment] 2017-03-21 04:59
@alansouzati 
Please review this issue and let me know your thoughts on this...

**Comment by alansouzati** [comment] 2017-03-21 17:15
I'm glad you are using yarn. I cannot reproduce this issue in a Mac. I have to guess this is a problem with the CLI engine you are using. :(

I cannot think of a fix for this. Do you have any suggestion?

**Comment by arjunbm468** [comment] 2017-03-22 08:54
Not sure, whether yarn is causing the issue...

This link should give us some hint-
https://github.com/yarnpkg/yarn/issues/2785

**Comment by alansouzati** [comment] 2017-03-22 18:45
well based on my reading if definitely seems a yarn issue. Just to understand, why you are not sure?

**Comment by alansouzati** [comment] 2017-03-24 15:35
hey @arjunbm468 any updates here?

**Comment by alansouzati** [comment] 2017-03-31 23:58
I'm going to close this issue as I cannot reproduce it. feel free to reopen it if you still believe there is something to be fixed in Grommet core.

**Closed by alansouzati** 2017-03-31 23:58 UTC
Labels: this sprint, waiting
